apiVersion: v1 
kind: ConfigMap
metadata:
 namespace: roboshop
 name: user
 labels:
  component: user
  project: roboshop
  tier: app
data:
 MONGO: "true" 
 REDIS_URL: "redis://redis:6379" 
 #MONGO_URL: "mongodb://mongodb:27017/users"
 MONGO_URL: {{ .Values.configMap.MONGO_URL }}
